services:
  item-server:
    container_name: item-server-container
    hostname: item-server
    build:
      context: ../../artifactory
      dockerfile: /dockerfiles/item-server-dockerfile

  item-server-db:
    image: mysql:latest
    container_name: item-server-db
    restart: always
    env_file: "../../artifactory/env/item-server-db.env"